services:
  posgres:
    image: postgres
    container_name: local_pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_covoit
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./init-postgres/:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  dbdata6:
  local_pgdata:
  pgadmin-data:
